services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
  myapp:
    build: .
    depends_on:
      - postgres
    environment:
      - 'DATABASE_URL=postgres://myuser:secret@postgres:5432/mydatabase'
    ports:
      - '8000:8000'
